galaxy_info:
  author: Ryan Sinnet
  description: Install Ignition Gazebo
  company: Miso Robotics
  license: MIT
  min_ansible_version: 2.9
  platforms: # https://galaxy.ansible.com/api/v1/platforms/
    - name: Ubuntu
      versions:
        - artful
        - bionic
        - cosmic
        - disco
        - eoan
        - focal
        - groovy
        - jammy
        - precise
        - quantal
        - raring
        - saucy
        - trusty
        - utopic
        - vivid
        - wily
        - xenial
        - yakkety
        - zesty
    - name: Debian
      versions:
        - buster
        - jessie
        - stretch
  galaxy_tags: []
dependencies: []
